# Generated by Django 5.0.7 on 2024-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="images/profiles/default-user.png",
                null=True,
                upload_to="images/profiles/",
            ),
        ),
    ]
