# Generated by Django 5.0.7 on 2024-09-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="images/profiles/default-user.png",
                null=True,
                upload_to="images/profiles/",
            ),
        ),
    ]
