# Generated by Django 5.0.7 on 2024-09-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                default="images/projects/default-project.png",
                null=True,
                upload_to="images/projects/",
            ),
        ),
    ]
